version: 2
registries:
  visual-studio-securitytools:
    type: nuget-feed
    url: https://securitytools.pkgs.visualstudio.com/_packaging/Guardian/nuget/v3/index.json
    # token: ${{ secrets.NUGET_PRIVATE_REG_TOKEN }}
updates:
  - package-ecosystem: 'github-actions'
    # default location of '.github/workflows'
    directory: '/'
    open-pull-requests-limit: 10
    schedule:
      interval: 'weekly'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'eng/common/internal'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'eng/common/sdl'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'samples/FxExtensibility'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Adapter/MSTest.CoreAdapter'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Adapter/PlatformServices.Desktop'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Adapter/PlatformServices.Interface'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Adapter/PlatformServices.NetCore'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Adapter/PlatformServices.Portable'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Adapter/PlatformServices.Universal'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/Adapter/PlatformServices.WinUI'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/TestFramework/Extension.Core'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/TestFramework/Extension.Desktop'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/TestFramework/Extension.UWP'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/TestFramework/Extension.WinUI'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'src/TestFramework/MSTest.Core'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/ComponentTests/PlatformServices.Desktop.Component.Tests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/ComponentTests/TestAssets/SampleFrameworkExtensions'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/ComponentTests/TestAssets/TestProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/ComponentTests/TestAssets/TestProjectForAssemblyResolution'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/Automation.CLI'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/DiscoveryAndExecutionTests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/Smoke.E2E.Tests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/CompatTestProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/DataRowTestProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/DataSourceTestProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/DeploymentTestProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/DeploymentTestProjectNetCore'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/DesktopTestProjectx64Debug'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/DesktopTestProjectx64Release'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/DesktopTestProjectx86Debug'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/DesktopTestProjectx86Release'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/DoNotParallelizeTestProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/FSharpTestProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/FxExtensibilityTestProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/ParallelTestClass'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/ParallelTestMethods'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/TimeoutTestProject'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/E2ETests/TestAssets/TimeoutTestProjectNetCore'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/UnitTests/MSTest.Core.Unit.Tests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/UnitTests/MSTest.CoreAdapter.TestUtilities'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/UnitTests/MSTest.CoreAdapter.Unit.Tests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/UnitTests/PlatformServices.Desktop.Unit.Tests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/UnitTests/PlatformServices.NetCore.Unit.Tests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/UnitTests/PlatformServices.Portable.Unit.Tests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

  - package-ecosystem: 'nuget'
    directory: 'test/UnitTests/PlatformServices.Universal.Unit.Tests'
    open-pull-requests-limit: 10
    schedule:
      interval: 'daily'
    # target-branch: 'develop'
    # assignees:
    #   - assignee_one
    # reviewers:
    #   - reviewer_one

# Built with ‚ù§ by [Pipeline Foundation](https://pipeline.foundation)
