name: Download MSTest Packages

on:
  workflow_dispatch:
    inputs:
      mstest_version:
        description: 'MSTest version'
        required: true
        type: string
      mstest_engine_version:
        description: 'MSTest.Engine version'
        required: true
        type: string
      mtp_version:
        description: 'MTP version'
        required: true
        type: string

jobs:
  download-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          global-json-file: global.json

      - name: Download packages from test-tools feed
        run: |
          dotnet run .github/workflows/PackageDownloader.cs -- ${{ github.event.inputs.mstest_version }} ${{ github.event.inputs.mstest_engine_version }} ${{ github.event.inputs.mtp_version }}

      - name: Authenticate to nuget
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1.1.0
        id: nugetlogin
        with:
          user: MSTestFramework

      - name: Push to NuGet.org
        run: dotnet nuget push "./PackagesToPublish/*.nupkg" --api-key "${{ steps.nugetlogin.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
